name: Validate and merge Pull request
on:
  pull_request:
    types: opened, reopened
  workflow_dispatch:
    inputs:
      pr_number:
        type: string
        default: '0'
        description: Enter Pull Request number
jobs:
  validate_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: echo '{} ' >package.json
      - run: npm install modbus2mqtt/specification
      - run: if [ ${{ inputs.pr_number }} != 0 ]; then 
            echo PR_NUMBER=${{ inputs.pr_number }} >> $GITHUB_ENV
            fi
      - run: if [ "${{ github.event.number }}" > 0 ]; then 
           echo PR_NUMBER=${{ github.event.number }} >> $GITHUB_ENV
           fi
      - run: npx validate 
          
